### ISSUE TITLE
AttributeError: '_GzipStreamFile' object has no attribute '_checkReadable'

### ISSUE THREAD

**Issue by IvRRimum** [Smerity/gzipstream#6]
Hello,

I encounter this error when trying to write.

heres full error:

```
Importing dmoz...
Traceback (most recent call last):
  File "urlserver/import.py", line 21, in <module>
    ds.import_dump()
  File "./urlserver/datasources/__init__.py", line 62, in import_dump
    for i, row in self.iter_dump():
  File "./urlserver/datasources/__init__.py", line 102, in iter_dump
    f = self.open_dump()
  File "./urlserver/datasources/__init__.py", line 144, in open_dump
    return GzipStreamFile(f)
  File "/cosr/back/venv/src/gzipstream/gzipstream/gzipstreamfile.py", line 62, in __init__
    super(GzipStreamFile, self).__init__(self._gzipstream)
  File "/usr/lib64/python2.6/io.py", line 921, in __init__
    raw._checkReadable()
AttributeError: '_GzipStreamFile' object has no attribute '_checkReadable'
make: *** [import_local_data] Error 1

```

**Comment by IvRRimum** [comment]
This seems to be problem, when NO FILES EXISTS! Will investigate further
